/*
 * KEYPAD_config.h
 *
 * Created: 9/22/2024 9:05:17 PM
 *  Author: RAWAN
 */ 


#ifndef KEYPAD_CONFIG_H_
#define KEYPAD_CONFIG_H_


#define KEYPAD_COL_PORT	DIO_PORTD
#define KEYPAD_COL0_PIN	DIO_PIN0
#define KEYPAD_COL1_PIN	DIO_PIN1
#define KEYPAD_COL2_PIN	DIO_PIN2
#define KEYPAD_COL3_PIN	DIO_PIN3

#define KEYPAD_ROW_PORT	DIO_PORTD
#define KEYPAD_ROW0_PIN	DIO_PIN4
#define KEYPAD_ROW1_PIN	DIO_PIN5
#define KEYPAD_ROW2_PIN	DIO_PIN6
#define KEYPAD_ROW3_PIN	DIO_PIN7
 

#endif /* KEYPAD_CONFIG_H_ */